name: fia_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - requests
  - matplotlib
  - numpy=1.26.4
  - scikit-learn
  - imbalanced-learn
  - biopython
  - ansi2html
  - pyqt=5.15.7
  - qasync
  - pymol-open-source
  - pyqtwebengine
  - py3dmol
  - pip
  - mesa      # graphic compatibility for ARM MacOS
  - pywin32   # Only for Windowsn
      
