name: fia_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.2
  - requests=2.32.3
  - matplotlib=3.8.0
  - pyqt=5.12.3
  - pymol-open-source=3.0.0
  - pip
  - pip:
      - qasync
      - scikit-learn
      - imbalanced-learn
      - biopython==1.84
      - ansi2html
      - py3Dmol
